{% set name = "standardese" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 3
  skip: true  # [win and vc<14]
  run_exports:
    # standardese uses semantic versioning
    - {{ pin_subpackage("standardese") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    # Pin from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml to be compatible with conda-forge.
    - boost-cpp 1.74.0
    # Pulls in llvmdev (llvm-config) and provides the libclang headers that are not in libclang-cpp
    - clangdev
    - libclang
    - fmt
    - nlohmann_json
    - pugixml
    - inja
    - spdlog
  run:
    - {{ pin_compatible('libclang') }}
    # The preprocessor invoked by cppast
    - clangxx
    # For boost-program-options
    - boost-cpp 1.74.0

test:
  files:
    - sample.h
  requires:
    # To resolve #include statements in sample.h
    - {{ compiler('cxx') }}
  commands:
    - standardese sample.h

about:
  home: https://standardese.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The nextgen Doxygen for C++
  doc_url: https://standardese.github.io/
  dev_url: https://github.com/standardese/standardese

extra:
  recipe-maintainers:
    - saraedum

