// Copyright (C) 2021 Julian Rüth <julian.rueth@fsfe.org>
// This file is subject to the license terms in the LICENSE file
// found in the top-level directory of this distribution.

#ifndef STANDARDESE_INVENTORY_DOXYGEN_TAGFILE_HPP_INCLUDED
#define STANDARDESE_INVENTORY_DOXYGEN_TAGFILE_HPP_INCLUDED

#include <iosfwd>
#include <string>
#include <vector>
#include <type_safe/optional.hpp>

#include "../inventory.hpp"
#include "anchor.hpp"

namespace standardese::inventory::doxygen {

/// The contents of a [doxygen tagfile](https://www.doxygen.nl/manual/external.html).
///
/// Tagfiles are generated by [doxygen](https://www.doxygen.nl). Such
/// inventories can be used to establish links between the documentations of
/// different projects, i.e., they resolve documented entities to URLs.
/// Standardese also generates such inventories itself, see
/// [tagfile_generator]().
///
/// For the precise structure of a tagfile see the `writeTagFile`
/// implementations, https://github.com/doxygen/doxygen/search?q=writeTagFile.
struct tagfile : public inventory {
  static tagfile parse(const std::string& fname);

  friend std::istream& operator>>(std::istream&, tagfile&);
  friend std::ostream& operator<<(std::ostream&, const tagfile&);
};

}

#endif
