// Copyright (C) 2021 Julian Rüth <julian.rueth@fsfe.org>
// This file is subject to the license terms in the LICENSE file
// found in the top-level directory of this distribution.

#ifndef STANDARDESE_INVENTORY_SPHINX_DOCUMENTATION_SET_HPP_INCLUDED
#define STANDARDESE_INVENTORY_SPHINX_DOCUMENTATION_SET_HPP_INCLUDED

#include <iosfwd>
#include <string>
#include <vector>
#include <type_safe/optional.hpp>

#include "entry.hpp"
#include "../inventory.hpp"

namespace standardese::inventory::sphinx {

/// The contents of an [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) inventory file.
///
/// Intersphinx inventories are generated by
/// [Sphinx](https://www.sphinx-doc.org/en/master/index.html), a popular
/// documentation generator often used for Python projects. Such inventories
/// can be used to establish links between the documentations of different
/// projects, i.e., they resolve documented entities to URLs.
/// Standardese also generates such inventories itself, see
/// [inventory_generator]().
struct documentation_set : public inventory {
  static documentation_set parse(const std::string& fname);

  friend std::istream& operator>>(std::istream&, documentation_set&);
  friend std::ostream& operator<<(std::ostream&, const documentation_set&);

  std::string project;
  std::string version;

  std::vector<entry> entries;
};

}

#endif
